#!/usr/bin/env bash

set -euo pipefail

notices_init() {
    local output="$1"
    local artifact="$2"
    local source="$3"
    {
        printf 'THIRD-PARTY NOTICES\n'
        printf '===================\n\n'
        printf 'Generated by %s for %s.\n' "$source" "$artifact"
        printf 'The artifact contains the third-party components listed below.\n'
    } > "$output"
}

notices_append_file() {
    local output="$1"
    local title="$2"
    local source_label="$3"
    local source="$4"
    [[ -s "$source" ]] || {
        printf 'missing third-party license source: %s\n' "$source" >&2
        exit 1
    }
    {
        printf '\n\n================================================================\n'
        printf '%s\n' "$title"
        printf 'Source license file: %s\n\n' "$source_label"
        cat "$source"
        printf '\n'
    } >> "$output"
}

notices_append_url() {
    local output="$1"
    local title="$2"
    local url="$3"
    local downloaded="$4"
    if [[ ! -s "$downloaded" ]]; then
        curl --fail --location --retry 3 --silent --show-error "$url" --output "$downloaded"
    fi
    {
        printf '\n\n================================================================\n'
        printf '%s\n' "$title"
        printf 'License source: %s\n\n' "$url"
        cat "$downloaded"
        printf '\n'
    } >> "$output"
}

notices_append_gcc_runtime_licenses() {
    local output="$1"
    local cache_dir="$2"
    local gpl="$cache_dir/gpl-3.0.txt"
    local gcc_exception="$cache_dir/gcc-exception-3.1.txt"
    local lgpl="$cache_dir/lgpl-2.1.txt"

    notices_append_url \
        "$output" \
        "GCC libgfortran and libgcc_s — GPL-3.0 with GCC Runtime Library Exception 3.1" \
        "https://www.gnu.org/licenses/gpl-3.0.txt" \
        "$gpl"
    notices_append_url \
        "$output" \
        "GCC Runtime Library Exception 3.1" \
        "https://raw.githubusercontent.com/gcc-mirror/gcc/releases/gcc-15.2.0/COPYING.RUNTIME" \
        "$gcc_exception"
    notices_append_url \
        "$output" \
        "GCC libquadmath — LGPL-2.1" \
        "https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt" \
        "$lgpl"
}

notices_append_suite_sparse_config() {
    local output="$1"
    local source_root="$2"
    local work_dir="$3"
    local notice="$work_dir/suitesparse-config-notice.txt"

    {
        sed -n '4,8p' "$source_root/SuiteSparse_config/SuiteSparse_config.c"
        printf '\nThe BSD-3-Clause terms are reproduced below.\n\n'
        sed -n '8,$p' "$source_root/AMD/Doc/License.txt"
    } > "$notice"
    notices_append_file \
        "$output" \
        "SuiteSparse_config — BSD-3-Clause" \
        "SuiteSparse_config/SuiteSparse_config.c and SuiteSparse/AMD/Doc/License.txt" \
        "$notice"
}
