#!/usr/bin/env bash

set -euo pipefail

notices_init() {
    local output="$1"
    local artifact="$2"
    local source="$3"
    {
        printf 'THIRD-PARTY NOTICES\n'
        printf '===================\n\n'
        printf 'Generated by %s for %s.\n' "$source" "$artifact"
        printf 'The artifact contains the third-party components listed below.\n'
    } > "$output"
}

notices_append_file() {
    local output="$1"
    local title="$2"
    local source_label="$3"
    local source="$4"
    [[ -s "$source" ]] || {
        printf 'missing third-party license source: %s\n' "$source" >&2
        exit 1
    }
    {
        printf '\n\n================================================================\n'
        printf '%s\n' "$title"
        printf 'Source license file: %s\n\n' "$source_label"
        cat "$source"
        printf '\n'
    } >> "$output"
}
