#ifndef KOBLAS_INTERNAL_H
#define KOBLAS_INTERNAL_H
#include "koblas_kernels.h"
#define KOBLAS_JOIN_(a,b) a##b
#define KOBLAS_JOIN(a,b) KOBLAS_JOIN_(a,b)
#define KOBLAS_IMPL(name) KOBLAS_JOIN(name, KOBLAS_SUFFIX)
double koblas_dense_dot_scalar(const double *a, int32_t a_off, const double *b, int32_t b_off, int32_t len);
double koblas_dense_ssqd_scalar(const double *a, int32_t a_off, const double *b, int32_t b_off, int32_t len);
void koblas_dense_axpy_scalar(double *y, int32_t y_off, double alpha, const double *x, int32_t x_off, int32_t len);
void koblas_dense_axpy_arithmetic_scalar(double *y, int32_t y_off, double alpha, const double *x, int32_t x_off, int32_t len);
void koblas_dense_scale_scalar(double *v, int32_t v_off, double alpha, int32_t len);
double koblas_dense_nrm2_scalar(const double *v, int32_t v_off, int32_t len);
double koblas_dense_sum_scalar(const double *v, int32_t v_off, int32_t len);
double koblas_dense_asum_scalar(const double *v, int32_t v_off, int32_t len);
int32_t koblas_dense_iamax_scalar(const double *v, int32_t v_off, int32_t len);
void koblas_dense_gemm_tile_scalar(int32_t depth, const double *packed_a, int32_t a_off, const double *packed_b, int32_t b_off, double *c, int32_t c_off, int32_t ldc);
void koblas_dense_swap_scalar(double *a, int32_t a_off, double *b, int32_t b_off, int32_t len);
void koblas_dense_dot4_scalar(const double *a, int32_t a_off, int32_t stride, const double *b, int32_t b_off, int32_t len, double *out, int32_t out_off);
void koblas_dense_axpy4_scalar(double *y, int32_t y_off, const double *a, int32_t a_off, int32_t stride, double c0, double c1, double c2, double c3, int32_t len);
double koblas_dense_dot_axpy_scalar(double *y, int32_t y_off, double alpha, const double *a, int32_t a_off, const double *x, int32_t x_off, int32_t len);
void koblas_dense_rotm_scalar(double *x, int32_t x_off, int32_t x_stride, double *y, int32_t y_off, int32_t y_stride, int32_t len, double h11, double h12, double h21, double h22);
double koblas_sparse_dot_dense_scalar(const int32_t *indices, int32_t index_off, const double *values, int32_t value_off, int32_t len, const double *dense);
double koblas_sparse_dot_sparse_scalar(const int32_t *a_indices, const double *a_values, int32_t a_len, const int32_t *b_indices, const double *b_values, int32_t b_len);
void koblas_sparse_axpy_scalar(const int32_t *indices, int32_t index_off, const double *values, int32_t value_off, int32_t len, double alpha, double *dense);
void koblas_sparse_scatter_scalar(const int32_t *indices, int32_t index_off, const double *values, int32_t value_off, int32_t len, double *dense);
double koblas_sparse_nrm2_scalar(const int32_t *indices, int32_t index_off, int32_t len, const double *values);
void koblas_sparse_gather_scalar(const int32_t *indices, double *values, int32_t len, const double *dense);
void koblas_sparse_gather_zero_scalar(const int32_t *indices, double *values, int32_t len, double *dense);
void koblas_dense_trsm_tile_scalar(int32_t valid_rows, int32_t order, const double *packed_triangle, int32_t triangle_off, int32_t lower, int32_t unit_diag, double *x, int32_t x_off);
void koblas_dense_gemm_trsm_tile_scalar(int32_t depth, int32_t valid_rows, int32_t order, const double *packed_a, int32_t a_off, const double *packed_b, int32_t b_off, const double *packed_triangle, int32_t triangle_off, int32_t lower, int32_t unit_diag, double *x, int32_t x_off);
double koblas_dense_dot_sse2(const double *a, int32_t a_off, const double *b, int32_t b_off, int32_t len);
double koblas_dense_ssqd_sse2(const double *a, int32_t a_off, const double *b, int32_t b_off, int32_t len);
void koblas_dense_axpy_sse2(double *y, int32_t y_off, double alpha, const double *x, int32_t x_off, int32_t len);
void koblas_dense_axpy_arithmetic_sse2(double *y, int32_t y_off, double alpha, const double *x, int32_t x_off, int32_t len);
void koblas_dense_scale_sse2(double *v, int32_t v_off, double alpha, int32_t len);
double koblas_dense_nrm2_sse2(const double *v, int32_t v_off, int32_t len);
double koblas_dense_sum_sse2(const double *v, int32_t v_off, int32_t len);
double koblas_dense_asum_sse2(const double *v, int32_t v_off, int32_t len);
int32_t koblas_dense_iamax_sse2(const double *v, int32_t v_off, int32_t len);
void koblas_dense_gemm_tile_sse2(int32_t depth, const double *packed_a, int32_t a_off, const double *packed_b, int32_t b_off, double *c, int32_t c_off, int32_t ldc);
void koblas_dense_swap_sse2(double *a, int32_t a_off, double *b, int32_t b_off, int32_t len);
void koblas_dense_dot4_sse2(const double *a, int32_t a_off, int32_t stride, const double *b, int32_t b_off, int32_t len, double *out, int32_t out_off);
void koblas_dense_axpy4_sse2(double *y, int32_t y_off, const double *a, int32_t a_off, int32_t stride, double c0, double c1, double c2, double c3, int32_t len);
double koblas_dense_dot_axpy_sse2(double *y, int32_t y_off, double alpha, const double *a, int32_t a_off, const double *x, int32_t x_off, int32_t len);
void koblas_dense_rotm_sse2(double *x, int32_t x_off, int32_t x_stride, double *y, int32_t y_off, int32_t y_stride, int32_t len, double h11, double h12, double h21, double h22);
double koblas_sparse_dot_dense_sse2(const int32_t *indices, int32_t index_off, const double *values, int32_t value_off, int32_t len, const double *dense);
double koblas_sparse_dot_sparse_sse2(const int32_t *a_indices, const double *a_values, int32_t a_len, const int32_t *b_indices, const double *b_values, int32_t b_len);
void koblas_sparse_axpy_sse2(const int32_t *indices, int32_t index_off, const double *values, int32_t value_off, int32_t len, double alpha, double *dense);
void koblas_sparse_scatter_sse2(const int32_t *indices, int32_t index_off, const double *values, int32_t value_off, int32_t len, double *dense);
double koblas_sparse_nrm2_sse2(const int32_t *indices, int32_t index_off, int32_t len, const double *values);
void koblas_sparse_gather_sse2(const int32_t *indices, double *values, int32_t len, const double *dense);
void koblas_sparse_gather_zero_sse2(const int32_t *indices, double *values, int32_t len, double *dense);
void koblas_dense_trsm_tile_sse2(int32_t valid_rows, int32_t order, const double *packed_triangle, int32_t triangle_off, int32_t lower, int32_t unit_diag, double *x, int32_t x_off);
void koblas_dense_gemm_trsm_tile_sse2(int32_t depth, int32_t valid_rows, int32_t order, const double *packed_a, int32_t a_off, const double *packed_b, int32_t b_off, const double *packed_triangle, int32_t triangle_off, int32_t lower, int32_t unit_diag, double *x, int32_t x_off);
double koblas_dense_dot_avx2(const double *a, int32_t a_off, const double *b, int32_t b_off, int32_t len);
double koblas_dense_ssqd_avx2(const double *a, int32_t a_off, const double *b, int32_t b_off, int32_t len);
void koblas_dense_axpy_avx2(double *y, int32_t y_off, double alpha, const double *x, int32_t x_off, int32_t len);
void koblas_dense_axpy_arithmetic_avx2(double *y, int32_t y_off, double alpha, const double *x, int32_t x_off, int32_t len);
void koblas_dense_scale_avx2(double *v, int32_t v_off, double alpha, int32_t len);
double koblas_dense_nrm2_avx2(const double *v, int32_t v_off, int32_t len);
double koblas_dense_sum_avx2(const double *v, int32_t v_off, int32_t len);
double koblas_dense_asum_avx2(const double *v, int32_t v_off, int32_t len);
int32_t koblas_dense_iamax_avx2(const double *v, int32_t v_off, int32_t len);
void koblas_dense_gemm_tile_avx2(int32_t depth, const double *packed_a, int32_t a_off, const double *packed_b, int32_t b_off, double *c, int32_t c_off, int32_t ldc);
void koblas_dense_swap_avx2(double *a, int32_t a_off, double *b, int32_t b_off, int32_t len);
void koblas_dense_dot4_avx2(const double *a, int32_t a_off, int32_t stride, const double *b, int32_t b_off, int32_t len, double *out, int32_t out_off);
void koblas_dense_axpy4_avx2(double *y, int32_t y_off, const double *a, int32_t a_off, int32_t stride, double c0, double c1, double c2, double c3, int32_t len);
double koblas_dense_dot_axpy_avx2(double *y, int32_t y_off, double alpha, const double *a, int32_t a_off, const double *x, int32_t x_off, int32_t len);
void koblas_dense_rotm_avx2(double *x, int32_t x_off, int32_t x_stride, double *y, int32_t y_off, int32_t y_stride, int32_t len, double h11, double h12, double h21, double h22);
double koblas_sparse_dot_dense_avx2(const int32_t *indices, int32_t index_off, const double *values, int32_t value_off, int32_t len, const double *dense);
double koblas_sparse_dot_sparse_avx2(const int32_t *a_indices, const double *a_values, int32_t a_len, const int32_t *b_indices, const double *b_values, int32_t b_len);
void koblas_sparse_axpy_avx2(const int32_t *indices, int32_t index_off, const double *values, int32_t value_off, int32_t len, double alpha, double *dense);
void koblas_sparse_scatter_avx2(const int32_t *indices, int32_t index_off, const double *values, int32_t value_off, int32_t len, double *dense);
double koblas_sparse_nrm2_avx2(const int32_t *indices, int32_t index_off, int32_t len, const double *values);
void koblas_sparse_gather_avx2(const int32_t *indices, double *values, int32_t len, const double *dense);
void koblas_sparse_gather_zero_avx2(const int32_t *indices, double *values, int32_t len, double *dense);
void koblas_dense_trsm_tile_avx2(int32_t valid_rows, int32_t order, const double *packed_triangle, int32_t triangle_off, int32_t lower, int32_t unit_diag, double *x, int32_t x_off);
void koblas_dense_gemm_trsm_tile_avx2(int32_t depth, int32_t valid_rows, int32_t order, const double *packed_a, int32_t a_off, const double *packed_b, int32_t b_off, const double *packed_triangle, int32_t triangle_off, int32_t lower, int32_t unit_diag, double *x, int32_t x_off);
double koblas_dense_dot_neon(const double *a, int32_t a_off, const double *b, int32_t b_off, int32_t len);
double koblas_dense_ssqd_neon(const double *a, int32_t a_off, const double *b, int32_t b_off, int32_t len);
void koblas_dense_axpy_neon(double *y, int32_t y_off, double alpha, const double *x, int32_t x_off, int32_t len);
void koblas_dense_axpy_arithmetic_neon(double *y, int32_t y_off, double alpha, const double *x, int32_t x_off, int32_t len);
void koblas_dense_scale_neon(double *v, int32_t v_off, double alpha, int32_t len);
double koblas_dense_nrm2_neon(const double *v, int32_t v_off, int32_t len);
double koblas_dense_sum_neon(const double *v, int32_t v_off, int32_t len);
double koblas_dense_asum_neon(const double *v, int32_t v_off, int32_t len);
int32_t koblas_dense_iamax_neon(const double *v, int32_t v_off, int32_t len);
void koblas_dense_gemm_tile_neon(int32_t depth, const double *packed_a, int32_t a_off, const double *packed_b, int32_t b_off, double *c, int32_t c_off, int32_t ldc);
void koblas_dense_swap_neon(double *a, int32_t a_off, double *b, int32_t b_off, int32_t len);
void koblas_dense_dot4_neon(const double *a, int32_t a_off, int32_t stride, const double *b, int32_t b_off, int32_t len, double *out, int32_t out_off);
void koblas_dense_axpy4_neon(double *y, int32_t y_off, const double *a, int32_t a_off, int32_t stride, double c0, double c1, double c2, double c3, int32_t len);
double koblas_dense_dot_axpy_neon(double *y, int32_t y_off, double alpha, const double *a, int32_t a_off, const double *x, int32_t x_off, int32_t len);
void koblas_dense_rotm_neon(double *x, int32_t x_off, int32_t x_stride, double *y, int32_t y_off, int32_t y_stride, int32_t len, double h11, double h12, double h21, double h22);
double koblas_sparse_dot_dense_neon(const int32_t *indices, int32_t index_off, const double *values, int32_t value_off, int32_t len, const double *dense);
double koblas_sparse_dot_sparse_neon(const int32_t *a_indices, const double *a_values, int32_t a_len, const int32_t *b_indices, const double *b_values, int32_t b_len);
void koblas_sparse_axpy_neon(const int32_t *indices, int32_t index_off, const double *values, int32_t value_off, int32_t len, double alpha, double *dense);
void koblas_sparse_scatter_neon(const int32_t *indices, int32_t index_off, const double *values, int32_t value_off, int32_t len, double *dense);
double koblas_sparse_nrm2_neon(const int32_t *indices, int32_t index_off, int32_t len, const double *values);
void koblas_sparse_gather_neon(const int32_t *indices, double *values, int32_t len, const double *dense);
void koblas_sparse_gather_zero_neon(const int32_t *indices, double *values, int32_t len, double *dense);
void koblas_dense_trsm_tile_neon(int32_t valid_rows, int32_t order, const double *packed_triangle, int32_t triangle_off, int32_t lower, int32_t unit_diag, double *x, int32_t x_off);
void koblas_dense_gemm_trsm_tile_neon(int32_t depth, int32_t valid_rows, int32_t order, const double *packed_a, int32_t a_off, const double *packed_b, int32_t b_off, const double *packed_triangle, int32_t triangle_off, int32_t lower, int32_t unit_diag, double *x, int32_t x_off);
uint32_t koblas_kernel_reason(uint32_t id, uint32_t operation);
#endif
